version: "3.7"

services:
  ckan:
    container_name: ckan
    image: ckancr.azurecr.io/prod/ckan:2.9.latest
    logging:
      driver: "json-file"
      options:
         max-size: "150K"
         max-file: "10"
    environment:
    links:
# Commented out to use POSTGRESQL instead of docker db
#     - db
      - solr
      - redis
      - datapusher
    ports:
      - "0.0.0.0:${CKAN_PORT}:5000"
    volumes:
      - ckan_storage:/var/lib/ckan
      - ckan_app:/srv/app
      - ckan_etc:/etc
      - ckan_home:/home
    restart: always
    
  datapusher:
    container_name: datapusher
    image: ckancr.azurecr.io/prod/datapusher:latest
    logging:
      driver: "json-file"
      options:
         max-size: "150K"
         max-file: "10"
    ports:
      - "8800:8800"
    restart: always

  solr:
    container_name: solr
    image: ckancr.azurecr.io/dev/solr:latest
    command: -force
    logging:
      driver: "json-file"
      options:
         max-size: "150K"
         max-file: "10"
    ports:
      - "8983:8983"
    volumes:
      - solr_data:/opt/solr/server/solr/ckan/data/index
    restart: always
    
  redis:
    container_name: redis
    image: redis:alpine
    logging:
      driver: "json-file"
      options:
         max-size: "150K"
         max-file: "10"
    restart: always
    
volumes:
  ckan_storage:
  ckan_app:
  ckan_etc:
  solr_data:
  ckan_home: