version: "3"

services:
  ckan-dev:
    env_file:
      - .env
    build:
      context: ckan/
      dockerfile: Dockerfile.dev
      args:
         - TZ=${TZ}
         - CKAN_SITE_URL=${CKAN_SITE_URL}
         - CKAN_SQLALCHEMY_URL
         - CKAN__LOCALE_ORDER
         - CKAN__LOCALES_OFFERED
         - CKAN___SCHEMING__DATASET_SCHEMAS
         - CKAN___SCHEMING__PRESETS
         - CKAN__SEARCH__SHOW_ALL_TYPES
         - CKAN___LICENSES_GROUP_URL
         - CKAN__VIEWS__DEFAULT_VIEWS
         - CKAN___CKANEXT__GEOVIEW__OL_VIEWER__FORMAT
         - CKAN__ROOT_PATH
         - CKAN__PLUGINS
    links:
# Commented out to use POSTGRESQL instead of docker db
#     - db
      - solr
      - redis
      - datapusher
    ports:
      - "0.0.0.0:${CKAN_PORT}:5000"
    volumes:
      - ./src:/srv/app/src_extensions
      - ckan_storage:/var/lib/ckan
      - ckan_app:/srv/app
      - ckan_etc:/etc
      - ckan_home:/home
    restart: always
    
  datapusher:
    container_name: datapusher
    build:
      context: datapusher/
    ports:
      - "8800:8800"
    restart: always

# Commented out to use POSTGRESQL instead of docker db
#  db:
#    container_name: db
#    build:
#      context: postgresql/
#    volumes:
#      - pg_data:/var/lib/postgresql/data

  solr:
    container_name: solr
    build:
      context: solr/
    ports:
      - "8983:8983"
    volumes:
      - solr_data:/opt/solr/server/solr/ckan/data/index
    restart: always
    
  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    
volumes:
  ckan_storage:
# Commented out to use POSTGRESQL instead of docker db
#  pg_data:
  ckan_app:
  ckan_etc:
  solr_data:
  ckan_home:
